CREATE DATABASE Users;

USE Users;

CREATE TABLE User(
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
login VARCHAR(20) NOT NULL,
password VARCHAR(20) NOT NULL,
isAdmin BOOL DEFAULT FALSE
);